# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
  indexes:
    movie:
      properties:
        title: ~
        description: ~
        rating: ~
        releaseDate: ~
      persistence:
        driver: orm
        model: App\Movie\Domain\Entity\Movie
        provider: ~
        finder: ~
